/* columns.gen.ts — the live shape of public.*, generated by db/gen-columns.mjs.
 * Do not hand-edit: change db/supabase/*.sql, apply it, regenerate. */

/** Postgres type per column, in the order the database declares them. */
export const COLUMNS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
 "audit": {
  "id": "text",
  "company_id": "text",
  "entity": "text",
  "entity_id": "text",
  "action": "text",
  "field": "text",
  "old_value": "jsonb",
  "new_value": "jsonb",
  "reason": "text",
  "by_user_id": "uuid",
  "at": "timestamp with time zone"
 },
 "batch_assignments": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "user_id": "uuid",
  "role": "text",
  "permissions": "jsonb",
  "comments": "text",
  "assigned_by": "uuid",
  "assigned_at": "timestamp with time zone"
 },
 "batch_closings": {
  "batch_id": "text",
  "company_id": "text",
  "date": "date",
  "final_birds": "integer",
  "buyer": "text",
  "amount": "numeric",
  "remarks": "text",
  "closed_by": "uuid",
  "closed_at": "timestamp with time zone"
 },
 "batches": {
  "id": "text",
  "company_id": "text",
  "farm_id": "text",
  "shed_id": "text",
  "code": "text",
  "bird_type": "text",
  "breed": "text",
  "hatch_date": "date",
  "placement_date": "date",
  "start_date": "date",
  "initial_birds": "integer",
  "status": "text",
  "approximate_feed_tpd": "numeric",
  "manager_id": "uuid",
  "supervisor_id": "uuid",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "cash_counts": {
  "id": "text",
  "company_id": "text",
  "date": "date",
  "physical_cash": "numeric",
  "expected_cash": "numeric",
  "difference": "numeric",
  "closed_by": "uuid",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "cash_handovers": {
  "id": "text",
  "company_id": "text",
  "date": "date",
  "time": "time without time zone",
  "amount": "numeric",
  "from_user_id": "uuid",
  "to_user_id": "uuid",
  "reason": "text",
  "reference": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "companies": {
  "id": "text",
  "name": "text",
  "active": "boolean",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "company_users": {
  "user_id": "uuid",
  "company_id": "text",
  "role": "text"
 },
 "egg_collections": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "shed_id": "text",
  "date": "date",
  "good_trays": "integer",
  "broken_trays": "integer",
  "double_trays": "integer",
  "small_trays": "integer",
  "worker_name": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "egg_sale_bookings": {
  "id": "text",
  "company_id": "text",
  "shed_id": "text",
  "batch_id": "text",
  "date": "date",
  "trader_id": "text",
  "planned_trays": "integer",
  "grade": "text",
  "status": "text",
  "remarks": "text",
  "sale_entry_id": "text",
  "fulfilled_at": "timestamp with time zone",
  "cancel_reason": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "egg_wastages": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "shed_id": "text",
  "date": "date",
  "good_trays": "integer",
  "broken_trays": "integer",
  "double_trays": "integer",
  "small_trays": "integer",
  "reason": "text",
  "remarks": "text",
  "worker_name": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "farms": {
  "id": "text",
  "company_id": "text",
  "name": "text",
  "location": "text",
  "contact_mobile": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "feed_consumption": {
  "id": "text",
  "company_id": "text",
  "shed_id": "text",
  "batch_id": "text",
  "date": "date",
  "tonnes": "numeric",
  "formula_id": "text",
  "formula_version": "integer",
  "formula_name": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "feed_consumption_deductions": {
  "consumption_id": "text",
  "position": "integer",
  "ingredient": "text",
  "kg": "numeric"
 },
 "feed_formula_items": {
  "formula_id": "text",
  "position": "integer",
  "ingredient": "text",
  "kg_per_tonne": "numeric"
 },
 "feed_formulas": {
  "id": "text",
  "company_id": "text",
  "shed_id": "text",
  "name": "text",
  "family_id": "text",
  "version": "integer",
  "effective_from": "date",
  "status": "text",
  "change_reason": "text",
  "superseded_at": "timestamp with time zone",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "feed_round_logs": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "shed_id": "text",
  "date": "date",
  "round": "text",
  "status": "text",
  "at": "time without time zone",
  "worker_name": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "feed_stock": {
  "id": "text",
  "company_id": "text",
  "ingredient": "text",
  "date": "date",
  "kind": "text",
  "qty_kg": "numeric",
  "rate_per_kg": "numeric",
  "shed_id": "text",
  "batch_id": "text",
  "supplier": "text",
  "purchase_ref": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "finance_txns": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "godown": "boolean",
  "date": "date",
  "kind": "text",
  "amount": "numeric",
  "category": "text",
  "counterparty": "text",
  "ref_id": "text",
  "purchase_id": "text",
  "sale_id": "text",
  "payment_method": "text",
  "split": "jsonb",
  "time": "time without time zone",
  "handled_by": "uuid",
  "handed_to": "text",
  "authorized_by": "uuid",
  "reference": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "ingredients": {
  "name": "text",
  "added_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "medicine_items": {
  "id": "text",
  "company_id": "text",
  "name": "text",
  "category": "text",
  "unit": "text",
  "active": "boolean",
  "low_stock_threshold": "numeric",
  "specifications": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "medicine_stock": {
  "id": "text",
  "company_id": "text",
  "medicine_id": "text",
  "date": "date",
  "kind": "text",
  "qty": "numeric",
  "rate_per_unit": "numeric",
  "amount": "numeric",
  "shed_id": "text",
  "batch_id": "text",
  "supplier": "text",
  "purchase_ref": "text",
  "lot_number": "text",
  "expiry_date": "date",
  "reason": "text",
  "used_by": "text",
  "vaccination_id": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "mortality": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "shed_id": "text",
  "date": "date",
  "count": "integer",
  "worker_name": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "profiles": {
  "id": "uuid",
  "legacy_id": "text",
  "name": "text",
  "mobile": "text",
  "role": "text",
  "initials": "text",
  "active": "boolean",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "receipt_counters": {
  "company_id": "text",
  "scope": "text",
  "day": "date",
  "next_value": "integer"
 },
 "sale_entries": {
  "id": "text",
  "company_id": "text",
  "trader_id": "text",
  "date": "date",
  "pricing": "text",
  "rate_good": "numeric",
  "rate_broken": "numeric",
  "rate_double": "numeric",
  "rate_small": "numeric",
  "amount": "numeric",
  "cash": "numeric",
  "phonepe": "numeric",
  "advance": "numeric",
  "labor_charge": "numeric",
  "cash_handled_by": "uuid",
  "cash_time": "time without time zone",
  "cash_reference": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_by": "uuid",
  "updated_at": "timestamp with time zone"
 },
 "sale_entry_lines": {
  "sale_entry_id": "text",
  "position": "integer",
  "shed_id": "text",
  "good_trays": "integer",
  "broken_trays": "integer",
  "double_trays": "integer",
  "small_trays": "integer"
 },
 "sale_logs": {
  "id": "text",
  "company_id": "text",
  "shed_id": "text",
  "batch_id": "text",
  "date": "date",
  "trays": "integer",
  "grade": "text",
  "status": "text",
  "worker_name": "text",
  "remarks": "text",
  "acknowledged_by": "uuid",
  "acknowledged_at": "timestamp with time zone",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "sheds": {
  "id": "text",
  "company_id": "text",
  "farm_id": "text",
  "name": "text",
  "capacity": "integer",
  "status": "text",
  "farm_supervisor_id": "uuid",
  "financial_supervisor_id": "uuid",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "support_messages": {
  "id": "text",
  "company_id": "text",
  "user_id": "uuid",
  "name": "text",
  "mobile": "text",
  "subject": "text",
  "message": "text",
  "role": "text",
  "at": "timestamp with time zone",
  "handled_at": "timestamp with time zone",
  "handled_by": "text"
 },
 "tasks": {
  "id": "text",
  "company_id": "text",
  "title": "text",
  "date": "date",
  "time": "time without time zone",
  "assigned_user_id": "uuid",
  "farm_id": "text",
  "shed_id": "text",
  "batch_id": "text",
  "priority": "text",
  "status": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "trader_txns": {
  "id": "text",
  "company_id": "text",
  "trader_id": "text",
  "date": "date",
  "kind": "text",
  "trays": "integer",
  "rate": "numeric",
  "amount": "numeric",
  "ref_id": "text",
  "sale_id": "text",
  "payment_method": "text",
  "split": "jsonb",
  "time": "time without time zone",
  "handled_by": "uuid",
  "handed_to": "text",
  "authorized_by": "uuid",
  "reference": "text",
  "remarks": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone"
 },
 "traders": {
  "id": "text",
  "company_id": "text",
  "name": "text",
  "mobile": "text",
  "gstin": "text",
  "address": "text",
  "opening_balance": "numeric",
  "active": "boolean",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "vaccination_template_items": {
  "template_id": "text",
  "position": "integer",
  "relative_day": "integer",
  "vaccine_name": "text",
  "reminder_days_before": "integer",
  "dose": "text",
  "route": "text",
  "remarks": "text"
 },
 "vaccination_templates": {
  "id": "text",
  "company_id": "text",
  "name": "text",
  "bird_type": "text",
  "active": "boolean",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 },
 "vaccinations": {
  "id": "text",
  "company_id": "text",
  "batch_id": "text",
  "shed_id": "text",
  "relative_day": "integer",
  "vaccine_name": "text",
  "scheduled_date": "date",
  "reminder_days_before": "integer",
  "dose": "text",
  "route": "text",
  "remarks": "text",
  "status": "text",
  "completed_date": "date",
  "completed_at": "timestamp with time zone",
  "completed_by": "text",
  "actual_dose": "text",
  "completion_remarks": "text",
  "cancelled_at": "timestamp with time zone",
  "cancelled_by": "text",
  "cancellation_reason": "text",
  "created_by": "uuid",
  "created_at": "timestamp with time zone",
  "updated_at": "timestamp with time zone"
 }
} as const;

/** Primary key columns per table — the conflict target every upsert rides on. */
export const PRIMARY_KEYS: Readonly<Record<string, readonly string[]>> = {
 "audit": [
  "id"
 ],
 "batch_assignments": [
  "id"
 ],
 "batch_closings": [
  "batch_id"
 ],
 "batches": [
  "id"
 ],
 "cash_counts": [
  "id"
 ],
 "cash_handovers": [
  "id"
 ],
 "companies": [
  "id"
 ],
 "company_users": [
  "user_id",
  "company_id"
 ],
 "egg_collections": [
  "id"
 ],
 "egg_sale_bookings": [
  "id"
 ],
 "egg_wastages": [
  "id"
 ],
 "farms": [
  "id"
 ],
 "feed_consumption": [
  "id"
 ],
 "feed_consumption_deductions": [
  "consumption_id",
  "position"
 ],
 "feed_formula_items": [
  "formula_id",
  "position"
 ],
 "feed_formulas": [
  "id"
 ],
 "feed_round_logs": [
  "id"
 ],
 "feed_stock": [
  "id"
 ],
 "finance_txns": [
  "id"
 ],
 "ingredients": [
  "name"
 ],
 "medicine_items": [
  "id"
 ],
 "medicine_stock": [
  "id"
 ],
 "mortality": [
  "id"
 ],
 "profiles": [
  "id"
 ],
 "receipt_counters": [
  "company_id",
  "scope",
  "day"
 ],
 "sale_entries": [
  "id"
 ],
 "sale_entry_lines": [
  "sale_entry_id",
  "position"
 ],
 "sale_logs": [
  "id"
 ],
 "sheds": [
  "id"
 ],
 "support_messages": [
  "id"
 ],
 "tasks": [
  "id"
 ],
 "trader_txns": [
  "id"
 ],
 "traders": [
  "id"
 ],
 "vaccination_template_items": [
  "template_id",
  "position"
 ],
 "vaccination_templates": [
  "id"
 ],
 "vaccinations": [
  "id"
 ]
} as const;

export const TABLE_NAMES = Object.keys(COLUMNS);
