/**
 * Emits src/services/supabase/columns.gen.ts — what columns each public table has, and of
 * which Postgres type. The browser cannot read information_schema through RLS, and the sync
 * engine needs exactly the cast rules db/import-localstorage.mjs reads from there, so the
 * answer is taken once from the live schema and checked in.
 *
 *   node --env-file=.env db/gen-columns.mjs
 *
 * Re-run it after any new db/supabase/*.sql lands, same as the import expects.
 */
import fs from 'node:fs';
import pg from 'pg';

const u = new URL(process.env.POSTGRES_URL_NON_POOLING.replace(/^postgres:/, 'postgresql:'));
const c = new pg.Client({
  host: u.hostname, port: Number(u.port || 5432),
  user: decodeURIComponent(u.username), password: decodeURIComponent(u.password),
  database: u.pathname.slice(1) || 'postgres',
  ssl: process.env.SUPABASE_DB_CA
    ? { ca: fs.readFileSync(process.env.SUPABASE_DB_CA, 'utf8') }
    : { rejectUnauthorized: false },
});
await c.connect();

const cols = await c.query(`
  select table_name, column_name, data_type
  from information_schema.columns
  where table_schema = 'public'
  order by 1, ordinal_position`);
const pks = await c.query(`
  select tc.table_name, string_agg(kcu.column_name, ',' order by kcu.ordinal_position) cols
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on kcu.constraint_name = tc.constraint_name and kcu.table_schema = tc.table_schema
  where tc.table_schema = 'public' and tc.constraint_type = 'PRIMARY KEY'
  group by 1`);
await c.end();

const byTable = new Map();
for (const r of cols.rows) {
  if (r.table_name.startsWith('v_')) continue;
  if (!byTable.has(r.table_name)) byTable.set(r.table_name, {});
  byTable.get(r.table_name)[r.column_name] = r.data_type;
}
const pkMap = Object.fromEntries(pks.rows.map(r => [r.table_name, r.cols.split(',')]));

const out = `/* columns.gen.ts — the live shape of public.*, generated by db/gen-columns.mjs.
 * Do not hand-edit: change db/supabase/*.sql, apply it, regenerate. */

/** Postgres type per column, in the order the database declares them. */
export const COLUMNS: Readonly<Record<string, Readonly<Record<string, string>>>> = ${JSON.stringify(Object.fromEntries(byTable), null, 1)} as const;

/** Primary key columns per table — the conflict target every upsert rides on. */
export const PRIMARY_KEYS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(pkMap, null, 1)} as const;

export const TABLE_NAMES = Object.keys(COLUMNS);
`;
fs.writeFileSync('src/services/supabase/columns.gen.ts', out);
console.log(`wrote src/services/supabase/columns.gen.ts — ${byTable.size} tables`);
